version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: mkdir ~/evo-x && cd ~/evo-x
      - run: sudo apt install curl
      - run: mkdir ~/bin && PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo  
      - run: repo init -u https://github.com/Evolution-X/manifest -b elle
      - run: repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run: . build/envsetup.sh
      - run: lunch evolution_lavender-userdebug
      - run: mka bacon -jX
