version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: git config --global user.email "tukaiari@gmail.com"
      - run: git config --global user.name "Arijit Roy"
      - run: curl -O https://raw.githubusercontent.com/arijit192/ab/main/su.sh && chmod +x su.sh && sudo ./su.sh
      - run: mkdir ~/evo-x && cd ~/evo-x
      - run: repo init --depth=1 -u https://github.com/Evolution-X/manifest -b elle
      - run: repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run: cd ~/evo-x && source build/envsetup.sh
      - run: cd ~/evo-x && lunch evolution_lavender-userdebug
      - run: cd ~/evo-x && mka bacon -jX 
