version: 2
jobs:
  build:
    machine:
      image: android:202102-01
    steps:
      - checkout
      - run: git config --global user.email "tukaiari@gmail.com"
      - run: git config --global user.name "Arijit Roy"
      #- run: sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig 
      - run: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      - run: mkdir ~/and && cd ~/and
      - run: repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b master --partial-clone --clone-filter=blob:limit=10M
      - run: repo sync
      - run: cd ~/and && source build/envsetup.sh
      - run: cd ~/and && lunch aosp_arm-eng 
      - run: cd ~/and && m
