version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: git config --global user.email "tukaiari@gmail.com"
      - run: git config --global user.name "Arijit Roy"
      - run: sudo apt update
      - run: sudo apt install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
      - run: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      - run: ssh-keygen -q -t rsa -N '' <<< ""$'\n'"y" 2>&1 >/dev/null && gpg --keyserver https://keyserver.ubuntu.com --search-keys cco3@android.com <<< $'2'
      - run: mkdir ~/aros && cd ~/aros && repo init --depth=1 -u https://source.codeaurora.org/platform/manifest.git -b release -m LA.UM.9.6.2.r1-04700-89xx.0.xml --repo-url=https://source.codeaurora.org/tools/repo.git --repo-branch=caf-stable && repo sync
      #- run: cd ~/aros && git clone -b arrow-11.0 https://github.com/ArrowOS-Devices/android_device_xiaomi_lavender.git device/xiaomi/lavender && repo sync --force
      - run: cd ~/aros && source build/envsetup.sh && choosecombo
      #- run: cd ~/aros && m bacon 
