version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: git config --global user.email "tukaiari@gmail.com"
      - run: git config --global user.name "Arijit Roy"
      - run: sudo apt update
      - run: sudo apt install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
      - run: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      - run: mkdir ~/an && cd ~/an && repo init --depth=1 -u git://github.com/LineageOS/android.git -b lineage-18.1 && repo sync
      - run: cd ~/an && echo "<manifest><remote name="gitlab" fetch="https://gitlab.com" /><project name="the-muppets/proprietary_vendor_xiaomi" path="vendor/xiaomi" remote="gitlab"/></manifest>
      - run: cd ~/an && source build/envsetup.sh && breakfast lavender && croot && brunch lavender
      #- run: cd ~/aros && m bacon 
